### PR TITLE
Update for FirebaseAuthUI

### PR DESCRIPTION
**Pull request by nohe427**
This updates the authentication quickstart to use FirebaseAuthUI. There were a few modifications needed to make the quickstart run smoothly again after updating to FirebaseAuthUI. These modifications included but was not limited to:

-  update the gradle version of the project
- set the minimum android version to 19 (required for auth ui)
- update cocoapods to their latest version
- remove the login page as firebase ui provides its own page
- implement routing for forgotten password etc...
- add a profile screen
- update cleartext security rules so using firebase emulators on the latest android version work well

### CODE REVIEW

**Comment by thatfiredev** [comment]
In other quickstarts we usually have a dedicated screen for Firebase UI. And we still demo the regular auth flows in other screens (one method per screen, see [quickstart-android](https://github.com/firebase/quickstart-android/tree/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin) as an example). Do we want to do the same for Flutter?

**Comment by kroikie** [comment]
LGTM

**Comment by kroikie** [comment]
@thatfiredev good point, I think we can have a follow up PR adding a non-FFUI screen.

**Comment by kroikie** [comment]
we have an issue to track:
https://github.com/firebase/quickstart-flutter/issues/13

**Pull request merged**
